-- MySQL Script generated by MySQL Workbench
-- Sun Mar 29 16:18:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema point_of_sale
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema point_of_sale
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `point_of_sale` DEFAULT CHARACTER SET utf8 ;
USE `point_of_sale` ;

-- -----------------------------------------------------
-- Table `point_of_sale`.`manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `point_of_sale`.`manufacturer` (
  `manufacturer_id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(100) NULL,
  `logo` TEXT NULL,
  `phone` VARCHAR(20) NULL,
  `email` VARCHAR(100) NULL,
  `address` VARCHAR(100) NULL,
  `website` VARCHAR(100) NULL,
  `time_create` DATETIME NULL,
  `time_edit` DATETIME NULL,
  `admin_create` BIGINT NULL,
  `admin_edit` BIGINT NULL,
  `ip_create` VARCHAR(48) NULL,
  `ip_edit` VARCHAR(48) NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`manufacturer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `point_of_sale`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `point_of_sale`.`brand` (
  `brand_id` VARCHAR(40) NOT NULL,
  `manufacturer_id` VARCHAR(40) NULL,
  `name` VARCHAR(100) NULL,
  `time_create` DATETIME NULL,
  `time_edit` DATETIME NULL,
  `admin_create` BIGINT NULL,
  `admin_edit` BIGINT NULL,
  `ip_create` VARCHAR(48) NULL,
  `ip_edit` VARCHAR(48) NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`brand_id`),
  INDEX `brand_manufacturer_id_idx` (`manufacturer_id` ASC),
  CONSTRAINT `brand_manufacturer_id`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `point_of_sale`.`manufacturer` (`manufacturer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `point_of_sale`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `point_of_sale`.`item` (
  `item_id` VARCHAR(40) NOT NULL,
  `barcode` VARCHAR(40) NULL,
  `name` VARCHAR(100) NULL,
  `description` TEXT NULL,
  `brand_id` VARCHAR(40) NULL,
  `type` VARCHAR(100) NULL,
  `model` VARCHAR(100) NULL,
  `size` VARCHAR(100) NULL,
  `weight` VARCHAR(100) NULL,
  `color` VARCHAR(100) NULL,
  `price` DOUBLE NULL,
  `discount` DOUBLE NULL,
  `time_create` DATETIME NULL,
  `time_edit` DATETIME NULL,
  `admin_create` BIGINT NULL,
  `admin_edit` BIGINT NULL,
  `ip_create` VARCHAR(48) NULL,
  `ip_edit` VARCHAR(48) NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`item_id`),
  INDEX `item_brand_id_idx` (`brand_id` ASC),
  CONSTRAINT `item_brand_id`
    FOREIGN KEY (`brand_id`)
    REFERENCES `point_of_sale`.`brand` (`brand_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `point_of_sale`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `point_of_sale`.`customer` (
  `customer_id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(100) NULL,
  `customer_type_id` VARCHAR(5) NULL,
  `gender` CHAR(1) NULL,
  `birth_day` DATE NULL,
  `phone` VARCHAR(20) NULL,
  `email` VARCHAR(100) NULL,
  `address` VARCHAR(100) NULL,
  `website` VARCHAR(100) NULL,
  `public` TINYINT(1) NULL DEFAULT 0,
  `default_data` TINYINT(1) NULL DEFAULT 0,
  `time_create` DATETIME NULL,
  `time_edit` DATETIME NULL,
  `admin_create` BIGINT NULL,
  `admin_edit` BIGINT NULL,
  `ip_create` VARCHAR(48) NULL,
  `ip_edit` VARCHAR(48) NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `point_of_sale`.`payment_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `point_of_sale`.`payment_method` (
  `payment_method_id` CHAR(2) NOT NULL,
  `name` VARCHAR(100) NULL,
  `sort_order` INT NULL,
  `default_data` TINYINT(1) NULL DEFAULT 0,
  `time_create` DATETIME NULL,
  `time_edit` DATETIME NULL,
  `admin_create` BIGINT NULL,
  `admin_edit` BIGINT NULL,
  `ip_create` VARCHAR(48) NULL,
  `ip_edit` VARCHAR(48) NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`payment_method_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `point_of_sale`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `point_of_sale`.`store` (
  `store_id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(45) NULL,
  `phone` VARCHAR(20) NULL,
  `email` VARCHAR(100) NULL,
  `address` VARCHAR(100) NULL,
  `website` VARCHAR(100) NULL,
  `public` TINYINT(1) NULL DEFAULT 0,
  `default_data` TINYINT(1) NULL DEFAULT 0,
  `time_create` DATETIME NULL,
  `time_edit` DATETIME NULL,
  `admin_create` BIGINT NULL,
  `admin_edit` BIGINT NULL,
  `ip_create` VARCHAR(48) NULL,
  `ip_edit` VARCHAR(48) NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`store_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `point_of_sale`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `point_of_sale`.`sales` (
  `sales_id` VARCHAR(40) NOT NULL,
  `store_id` VARCHAR(40) NULL,
  `customer_id` VARCHAR(40) NULL,
  `invoice` VARCHAR(32) NULL,
  `subtotal` DOUBLE NULL,
  `discount` DOUBLE NULL,
  `grand_total` DOUBLE NULL,
  `payment_method_id` CHAR(2) NULL,
  `payment_cash` DOUBLE NULL,
  `payment_change` VARCHAR(45) NULL,
  `time_create` DATETIME NULL,
  `seller_create` BIGINT NULL,
  `ip_create` VARCHAR(48) NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`sales_id`),
  INDEX `sales_customer_id_idx` (`customer_id` ASC),
  INDEX `sales_sales_idx` (`payment_method_id` ASC),
  INDEX `sales_store_id_idx` (`store_id` ASC),
  CONSTRAINT `sales_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `point_of_sale`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sales_payment_method_id`
    FOREIGN KEY (`payment_method_id`)
    REFERENCES `point_of_sale`.`payment_method` (`payment_method_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sales_store_id`
    FOREIGN KEY (`store_id`)
    REFERENCES `point_of_sale`.`store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `point_of_sale`.`sales_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `point_of_sale`.`sales_detail` (
  `sales_detail_id` VARCHAR(40) NOT NULL,
  `store_id` VARCHAR(40) NULL,
  `sales_id` VARCHAR(40) NULL,
  `customer_id` VARCHAR(40) NULL,
  `item_id` VARCHAR(40) NULL,
  `quantity` INT NULL,
  `price` DOUBLE NULL,
  `discount` DOUBLE NULL,
  `subtotal` DOUBLE NULL,
  `time_create` DATETIME NULL,
  `seller_create` BIGINT NULL,
  `ip_create` VARCHAR(48) NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`sales_detail_id`),
  INDEX `sales_item_id_idx` (`item_id` ASC),
  INDEX `sales_customer_id_idx` (`customer_id` ASC),
  INDEX `sales_detail_sales_id_idx` (`sales_id` ASC),
  INDEX `sales_detail_store_id_idx` (`store_id` ASC),
  CONSTRAINT `sales_detail_item_id`
    FOREIGN KEY (`item_id`)
    REFERENCES `point_of_sale`.`item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sales_detail_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `point_of_sale`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sales_detail_sales_id`
    FOREIGN KEY (`sales_id`)
    REFERENCES `point_of_sale`.`sales` (`sales_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sales_detail_store_id`
    FOREIGN KEY (`store_id`)
    REFERENCES `point_of_sale`.`store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `point_of_sale`.`item_circulation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `point_of_sale`.`item_circulation` (
  `item_circulation_id` VARCHAR(40) NOT NULL,
  `store_id` VARCHAR(40) NULL,
  `item_id` VARCHAR(40) NULL,
  `ready_stock_in` INT NULL,
  `ready_stock_out` INT NULL,
  `warehouse_stock_in` INT NULL,
  `warehouse_stock_out` INT NULL,
  `description` TEXT NULL,
  `time_create` DATETIME NULL,
  `time_edit` DATETIME NULL,
  `admin_create` BIGINT NULL,
  `admin_edit` BIGINT NULL,
  `ip_create` VARCHAR(48) NULL,
  `ip_edit` VARCHAR(48) NULL,
  `active` TINYINT(1) NULL,
  PRIMARY KEY (`item_circulation_id`),
  INDEX `item_circulation_item_id_idx` (`item_id` ASC),
  INDEX `item_circulation_store_id_idx` (`store_id` ASC),
  CONSTRAINT `item_circulation_item_id`
    FOREIGN KEY (`item_id`)
    REFERENCES `point_of_sale`.`item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `item_circulation_store_id`
    FOREIGN KEY (`store_id`)
    REFERENCES `point_of_sale`.`store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `point_of_sale`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `point_of_sale`.`supplier` (
  `supplier_id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(100) NULL,
  `supplier_type_id` VARCHAR(5) NULL,
  `gender` CHAR(1) NULL,
  `birth_day` DATE NULL,
  `phone` VARCHAR(20) NULL,
  `email` VARCHAR(100) NULL,
  `address` VARCHAR(100) NULL,
  `website` VARCHAR(100) NULL,
  `time_create` DATETIME NULL,
  `time_edit` DATETIME NULL,
  `admin_create` BIGINT NULL,
  `admin_edit` BIGINT NULL,
  `ip_create` VARCHAR(48) NULL,
  `ip_edit` VARCHAR(48) NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`supplier_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `point_of_sale`.`purchase_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `point_of_sale`.`purchase_status` (
  `purchase_status` CHAR(3) NOT NULL,
  `name` VARCHAR(100) NULL,
  `icon_sm` VARCHAR(100) NULL,
  `icon_md` VARCHAR(100) NULL,
  `icon_lg` VARCHAR(100) NULL,
  `icon_xl` VARCHAR(100) NULL,
  `sort_order` INT NULL,
  `default_data` TINYINT(1) NULL DEFAULT 0,
  `time_create` DATETIME NULL,
  `time_edit` DATETIME NULL,
  `admin_create` BIGINT NULL,
  `admin_edit` BIGINT NULL,
  `ip_create` VARCHAR(48) NULL,
  `ip_edit` VARCHAR(48) NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`purchase_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `point_of_sale`.`purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `point_of_sale`.`purchase` (
  `purchase_id` VARCHAR(40) NOT NULL,
  `store_id` VARCHAR(40) NULL,
  `item_id` VARCHAR(40) NULL,
  `supplier_id` VARCHAR(40) NULL,
  `price` DOUBLE NULL,
  `discount` DOUBLE NULL,
  `purchase_status_id` CHAR(3) NULL,
  `time_create` DATETIME NULL,
  `time_edit` DATETIME NULL,
  `admin_create` BIGINT NULL,
  `admin_edit` BIGINT NULL,
  `ip_create` VARCHAR(48) NULL,
  `ip_edit` VARCHAR(48) NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  `quantity` INT NULL,
  PRIMARY KEY (`purchase_id`),
  INDEX `purchase_item_id_idx` (`item_id` ASC),
  INDEX `purchase_supplier_id_idx` (`supplier_id` ASC),
  INDEX `purchase_purchase_status_id_idx` (`purchase_status_id` ASC),
  INDEX `purchase_store_id_idx` (`store_id` ASC),
  CONSTRAINT `purchase_item_id`
    FOREIGN KEY (`item_id`)
    REFERENCES `point_of_sale`.`item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `purchase_supplier_id`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `point_of_sale`.`supplier` (`supplier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `purchase_purchase_status_id`
    FOREIGN KEY (`purchase_status_id`)
    REFERENCES `point_of_sale`.`purchase_status` (`purchase_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `purchase_store_id`
    FOREIGN KEY (`store_id`)
    REFERENCES `point_of_sale`.`store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `point_of_sale`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `point_of_sale`.`admin` (
  `admin_id` VARCHAR(40) NOT NULL,
  `store_id` VARCHAR(40) NULL,
  `name` VARCHAR(100) NULL,
  `level_id` VARCHAR(40) NULL,
  `gender` CHAR(1) NULL,
  `birth_day` DATE NULL,
  `phone` VARCHAR(20) NULL,
  `email` VARCHAR(100) NULL,
  `address` VARCHAR(100) NULL,
  `website` VARCHAR(100) NULL,
  `time_create` DATETIME NULL,
  `time_edit` DATETIME NULL,
  `admin_create` BIGINT NULL,
  `admin_edit` BIGINT NULL,
  `ip_create` VARCHAR(48) NULL,
  `ip_edit` VARCHAR(48) NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`admin_id`),
  INDEX `admin_store_id_idx` (`store_id` ASC),
  CONSTRAINT `admin_store_id`
    FOREIGN KEY (`store_id`)
    REFERENCES `point_of_sale`.`store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `point_of_sale`.`seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `point_of_sale`.`seller` (
  `seller_id` VARCHAR(40) NOT NULL,
  `store_id` VARCHAR(40) NULL,
  `name` VARCHAR(100) NULL,
  `level_id` VARCHAR(40) NULL,
  `gender` CHAR(1) NULL,
  `birth_day` DATE NULL,
  `phone` VARCHAR(20) NULL,
  `email` VARCHAR(100) NULL,
  `address` VARCHAR(100) NULL,
  `website` VARCHAR(100) NULL,
  `time_create` DATETIME NULL,
  `time_edit` DATETIME NULL,
  `admin_create` BIGINT NULL,
  `admin_edit` BIGINT NULL,
  `ip_create` VARCHAR(48) NULL,
  `ip_edit` VARCHAR(48) NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`seller_id`),
  INDEX `seller_store_id_idx` (`store_id` ASC),
  CONSTRAINT `seller_store_id`
    FOREIGN KEY (`store_id`)
    REFERENCES `point_of_sale`.`store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `point_of_sale`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `point_of_sale`.`stock` (
  `stock_id` VARCHAR(40) NOT NULL,
  `store_id` VARCHAR(40) NULL,
  `item_id` VARCHAR(40) NULL,
  `ready_stock` INT NULL,
  `warehouse_stock` INT NULL,
  `time_create` DATETIME NULL,
  `time_edit` DATETIME NULL,
  `admin_create` BIGINT NULL,
  `admin_edit` BIGINT NULL,
  `ip_create` VARCHAR(48) NULL,
  `ip_edit` VARCHAR(48) NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`stock_id`),
  INDEX `stock_store_id_idx` (`store_id` ASC),
  INDEX `stock_item_id_idx` (`item_id` ASC),
  CONSTRAINT `stock_store_id`
    FOREIGN KEY (`store_id`)
    REFERENCES `point_of_sale`.`store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `stock_item_id`
    FOREIGN KEY (`item_id`)
    REFERENCES `point_of_sale`.`item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
